"""Read-only, Setup-only interpretation of the supported empty release.

Legacy preflight deliberately requires a project. Only an unchanged operational
release skeleton with *no* lifecycle footprint can be bootstrap-eligible before
one exists. Missing state alone is never evidence of freshness. No marker or
placeholder is written, and the ordinary preflight result is left unchanged on
any uncertainty. This proof is recomputed by both readiness and the start gate.

Two Console-owned artifacts are accepted beside the release skeleton because
they exist by design the moment the Console serves a Runtime and never carry
Runtime lifecycle state:

- `web_console_data/` is the Console's own non-authoritative data directory
  (setup drafts, instance metadata, server logs). The Setup wizard itself
  cannot record Steps 1-3 without creating it, so requiring its absence would
  make first-project bootstrap unreachable for any self-hosted Runtime.
- `control/supervisor_control.json` is accepted only in its factory-neutral
  form (see `_neutral_control_store`): zero counters, no pause history, and
  nothing but the optional fixed-policy pair. Anything else in it — and every
  other operational entry anywhere in the tree — still fails the proof.
"""
from __future__ import annotations

import errno
import hashlib
import json
import os
from pathlib import Path

import web_console_runtime_create as creation

# These execute or validate bootstrap / Runtime control. Console presentation,
# documentation and test changes must not invalidate an already-created Runtime.
CORE_SCRIPTS = (
    "executor_claim.py", "executor_completion.py", "executor_fence.py",
    "fv_sandbox.py", "migrate_goal_anchor.py", "preflight.py",
    "resume_human_review.py", "start_project.py", "supervisor_control.py",
    "provider_usage.py",
)
MAX_TREE_ENTRIES = 10000
MAX_FILE_BYTES = 16 * 1024 * 1024

CONSOLE_ROOT_ENTRIES = frozenset({"web_console_data"})
CONSOLE_CONTROL_ENTRIES = frozenset({"supervisor_control.json"})
NEUTRAL_PAUSE = {"status": "RUNNING", "requested_at": None, "mode": None,
                 "resumed_at": None}

# These execute or validate bootstrap / Runtime control. Console presentation,
# documentation and test changes must not invalidate an already-created Runtime.
CORE_SCRIPTS = (
    "executor_claim.py", "executor_completion.py", "executor_fence.py",
    "fv_sandbox.py", "migrate_goal_anchor.py", "preflight.py",
    "resume_human_review.py", "start_project.py", "supervisor_control.py",
    "provider_usage.py",
)
MAX_TREE_ENTRIES = 10000
MAX_FILE_BYTES = 16 * 1024 * 1024


def _files(directory: Path) -> set[str]:
    """Bounded inventory, rejecting links including those inside bytecode caches."""
    found = set()
    pending = [directory]
    count = 0
    while pending:
        parent = pending.pop()
        if creation.is_reparse(parent) or not parent.is_dir():
            raise ValueError("unsafe release directory")
        for path in parent.iterdir():
            count += 1
            if count > MAX_TREE_ENTRIES or creation.is_reparse(path):
                raise ValueError("unsafe or excessive release inventory")
            if path.is_dir():
                pending.append(path)
            elif path.is_file():
                relative = path.relative_to(directory)
                if "__pycache__" in relative.parts and path.suffix == ".pyc":
                    continue  # Generated by the read-only status probe.
                found.add(relative.as_posix())
            else:
                raise ValueError("non-regular release entry")
    return found


def _digest(path: Path) -> bytes:
    if creation.is_reparse(path) or not path.is_file():
        raise ValueError("missing or unsafe release file")
    if path.stat().st_size > MAX_FILE_BYTES:
        raise ValueError("release file exceeds bound")
    with path.open("rb") as stream:
        digest = hashlib.sha256()
        for chunk in iter(lambda: stream.read(65536), b""):
            digest.update(chunk)
        return digest.digest()


def _neutral_control_store(path: Path) -> bool:
    """True only for the factory-neutral SUPERVISOR-CONTROL-V1 store.

    Neutral means the state `supervisor_control.load_control` would otherwise
    synthesize on a missing file: zero revision and intervention generation,
    no pause history, and no unknown fields. The optional fixed-policy pair
    is validated by the Runtime's own helper so this check never grows a
    divergent dialect. Any lifecycle-signaling content fails here and would
    additionally fail the empty status-profile requirement upstream.
    """
    try:
        if path.stat().st_size > MAX_FILE_BYTES:
            return False
        value = json.loads(path.read_text(encoding="utf-8-sig"))
    except (OSError, UnicodeDecodeError, ValueError):
        return False
    if not isinstance(value, dict):
        return False
    allowed = {"schema_version", "revision", "intervention_generation",
               "pause", "supervisor_model", "supervisor_reasoning_effort",
               "updated_at"}
    if set(value) - allowed:
        return False
    try:
        import supervisor_control
    except Exception:
        return False  # Unverifiable control semantics fail closed.
    if value.get("schema_version") != supervisor_control.CONTROL_SCHEMA_VERSION:
        return False
    if value.get("revision") != 0 \
            or value.get("intervention_generation") != 0:
        return False
    if value.get("pause") != NEUTRAL_PAUSE:
        return False
    if ("supervisor_model" in value
            or "supervisor_reasoning_effort" in value) \
            and supervisor_control.supervisor_fixed_policy_from_control(
                value) is None:
        return False
    return value.get("updated_at") is None \
        or isinstance(value.get("updated_at"), str)


def _prove_empty_release(root: Path, installation: Path) -> bool:
    # Exact top-level / control / handoff inventories exclude *all* operational
    # history, even empty projects/logs directories, malformed pointers, orphaned
    # ledgers, locks, dispatches, STOP and HUMAN_REVIEW flags. Unknown means blocked.
    # The only accepted extras are the Console-owned entries above, and the
    # control-plane store only in its factory-neutral form.
    expected_root = (set(creation.RELEASE_FILES)
                     | set(creation.RELEASE_DIRECTORIES) | {"control", "handoff"})
    for directory, expected, console_allowed in (
            (root, expected_root, CONSOLE_ROOT_ENTRIES),
            (root / "control", set(creation.CONTROL_SEED_FILES),
             CONSOLE_CONTROL_ENTRIES),
            (root / "handoff", set(creation.HANDOFF_SEED_FILES),
             frozenset())):
        if creation.is_reparse(directory) or not directory.is_dir():
            return False
        extra = {p.name for p in directory.iterdir()} - expected
        if not extra <= console_allowed:
            return False
        if "supervisor_control.json" in extra and not _neutral_control_store(
                directory / "supervisor_control.json"):
            return False
    # Reject reparse ancestors rather than accepting an alias into another tree.
    for path in (root, *root.parents):
        if creation.is_reparse(path):
            return False
    required = set(creation.RELEASE_FILES)
    required.update("control/" + name for name in creation.CONTROL_SEED_FILES)
    required.update("handoff/" + name for name in creation.HANDOFF_SEED_FILES)
    required.update("scripts/" + name for name in CORE_SCRIPTS)
    required.update(creation.REQUIRED_RELEASE_PATHS)
    for name in creation.RELEASE_DIRECTORIES:
        actual = _files(root / name)
        supported = _files(installation / name)
        if not actual <= supported:
            return False
        if name == "profiles":
            if actual != supported:
                return False
            required.update("profiles/" + rel for rel in supported)
    for relative in required:
        if relative == "web_console/index.html":
            # UI can change independently of the installed Runtime semantics.
            if not (root / relative).is_file():
                return False
        elif _digest(root / relative) != _digest(installation / relative):
            return False
    return True


def interpret_fresh_install_preflight(*, root: Path, installation: Path,
                                      preflight: dict, status_doc: dict | None) -> dict:
    """Recognize only the exact missing-first-project legacy failure.

Draft/Goal/input/acknowledgement requirements remain separate required Setup
checks. This result grants bootstrap eligibility, never permission to run an
unbootstrapped Runtime. START_PROJECT still creates and binds lifecycle state.
    """
    if preflight.get("ok") or preflight.get("exit_code") != 1:
        return preflight
    if not isinstance(status_doc, dict) or status_doc.get("schema_version") != 1:
        return preflight
    empty = {
        "PROJECT_ID": None, "runtime_status": None, "project_status": None,
        "active_task": None, "last_authorized_dispatch": None,
        "active_task_claimed": False, "active_task_claim_recorded": False,
        "active_task_completion_status": None, "active_task_retired": False,
        "pending_interventions": 0, "last_consumed_message_id": None,
        "human_review": False, "stop": False, "supervisor_turn_inflight": None,
        "active_task_completion": None,
        "pause": {"status": "RUNNING", "requested_at": None,
                  "mode": None, "resumed_at": None},
    }
    if any(key not in status_doc or status_doc[key] != value
           for key, value in empty.items()):
        return preflight
    state = root / "control/project_state.json"
    missing = (state, root / "RESEARCH_STATE.md", root / "ZCODE_LAST_PROCESSED.txt")
    expected = ["PREFLIGHT: BLOCKED", "Mode: legacy", f"Runtime Root: {root}"]
    expected.extend(f"- missing: {path}" for path in missing)
    error = FileNotFoundError(errno.ENOENT, os.strerror(errno.ENOENT), str(state))
    expected.append(f"- project_state is missing or invalid: {state}: {error}")
    if str(preflight.get("head", "")).splitlines() != expected:
        return preflight  # Extra errors, truncation, timeouts and unknown dialects block.
    try:
        if not _prove_empty_release(root, installation):
            return preflight
    except (OSError, ValueError):
        return preflight
    return {**preflight, "ok": True,
            "head": "Fresh release verified: eligible for first-project bootstrap; "
                    "START_PROJECT will create lifecycle state.\n" + preflight["head"]}
